using Live2D.Cubism.Framework.Motion;
using Live2D.Cubism.Framework.MotionFade;
using UnityEngine;

/// <summary>
/// Loads the Mao Live2D model from its pre-built prefab in Resources/Live2D/Mao/
/// and maps PetController states (Idle / Clicked / Drag) to Live2D motions.
///
/// Uses pre-compiled .anim clips and Mao.fadeMotionList.asset to avoid the
/// "Not found motion from CubismFadeMotionList" runtime warning.
///
/// Motion mapping:
///   Idle    → mtn_01  (looping idle)
///   Clicked → mtn_02  (tap reaction, one-shot)
///   Drag    → mtn_03  (alternate, looping while dragged)
/// </summary>
public class Live2DController : MonoBehaviour
{
    private const string PrefabResourcePath   = "Live2D/Mao/Mao";
    private const string FadeMotionListPath   = "Live2D/Mao/Mao.fadeMotionList";
    private const string MotionBase           = "Live2D/Mao/motions/";
    private const string MotionIdle           = "mtn_01";
    private const string MotionClicked        = "mtn_02";
    private const string MotionDrag           = "mtn_03";

    private GameObject             _modelRoot;
    private CubismMotionController _motionCtrl;
    private string                 _currentState;

    private AnimationClip _clipIdle;
    private AnimationClip _clipClicked;
    private AnimationClip _clipDrag;

    private void Awake()
    {
        LoadModel();
    }

    public void PlayState(string state)
    {
        if (_motionCtrl == null)
        {
            Debug.LogWarning($"[L2D] PlayState({state}) skipped: motionCtrl is null");
            return;
        }
        if (state == _currentState) return;
        _currentState = state;
        Debug.Log($"[L2D] PlayState -> {state}");

        switch (state)
        {
            case "Idle":    PlayClip(_clipIdle,    isLoop: true);  break;
            case "Clicked": PlayClip(_clipClicked, isLoop: false); break;
            case "Drag":    PlayClip(_clipDrag,    isLoop: true);  break;
            default:
                Debug.LogWarning($"[Live2DController] Unknown state: {state}");
                break;
        }
    }

    private void LoadModel()
    {
        var prefab = Resources.Load<GameObject>(PrefabResourcePath);
        if (prefab == null)
        {
            Debug.LogError($"[Live2DController] Prefab not found at Resources/{PrefabResourcePath}");
            return;
        }

        _modelRoot = Instantiate(prefab, transform);
        _modelRoot.transform.localPosition = Vector3.zero;
        _modelRoot.transform.localScale    = Vector3.one;

        // Set up CubismFadeController with the pre-built fadeMotionList asset
        var fadeCtrl = _modelRoot.GetComponent<CubismFadeController>();
        if (fadeCtrl == null)
            fadeCtrl = _modelRoot.AddComponent<CubismFadeController>();

        var fadeMotionList = Resources.Load<CubismFadeMotionList>(FadeMotionListPath);
        if (fadeMotionList != null)
            fadeCtrl.CubismFadeMotionList = fadeMotionList;
        else
            Debug.LogWarning($"[Live2DController] fadeMotionList not found at Resources/{FadeMotionListPath}");

        // Use existing CubismMotionController from prefab; only add if missing
        _motionCtrl = _modelRoot.GetComponent<CubismMotionController>();
        if (_motionCtrl == null)
            _motionCtrl = _modelRoot.AddComponent<CubismMotionController>();

        // CubismMotionController.OnEnable() reads CubismFadeMotionList from CubismFadeController.
        // Since the prefab's OnEnable ran before we assigned fadeMotionList, we must
        // re-trigger OnEnable by toggling enabled so it picks up the correct list.
        _motionCtrl.enabled = false;
        _motionCtrl.enabled = true;

        // Load pre-compiled .anim clips (generated by Live2D SDK importer)
        _clipIdle    = LoadAnim(MotionIdle);
        _clipClicked = LoadAnim(MotionClicked);
        _clipDrag    = LoadAnim(MotionDrag);

        Debug.Log($"[L2D] motionCtrl={_motionCtrl} clipIdle={_clipIdle} clipClicked={_clipClicked} clipDrag={_clipDrag}");

        PlayState("Idle");

        Debug.Log("[Live2DController] Mao model loaded.");
    }

    private AnimationClip LoadAnim(string motionName)
    {
        var clip = Resources.Load<AnimationClip>(MotionBase + motionName);
        if (clip == null)
            Debug.LogWarning($"[Live2DController] AnimationClip not found: {MotionBase + motionName}");
        return clip;
    }

    private void PlayClip(AnimationClip clip, bool isLoop)
    {
        if (clip == null) return;
        _motionCtrl.PlayAnimation(clip,
            layerIndex: 0,
            priority:   CubismMotionPriority.PriorityNormal,
            isLoop:     isLoop);
    }
}
